# Generated by Django 6.0.2 on 2026-05-18 13:50

import django.db.models.deletion
import django_summernote.fields
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='JobCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, unique=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sub_categories', to='jobs.jobcategory')),
            ],
            options={
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('description', django_summernote.fields.SummernoteTextField()),
                ('max_salary', models.PositiveIntegerField(blank=True, null=True)),
                ('min_salary', models.PositiveIntegerField(blank=True, null=True)),
                ('location', models.CharField(blank=True, max_length=70, null=True)),
                ('job_type', models.CharField(choices=[('intern', 'Intern'), ('full_time', 'Full time'), ('part_time', 'Part time'), ('contract', 'Contract'), ('remote', 'Remote')], max_length=20)),
                ('posted_at', models.DateTimeField(auto_now_add=True)),
                ('deadline', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('company', models.ForeignKey(limit_choices_to={'user_type': 'company'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='jobs', to='jobs.jobcategory')),
            ],
            options={
                'indexes': [models.Index(fields=['company'], name='jobs_job_company_9ee5ea_idx'), models.Index(fields=['job_type'], name='jobs_job_job_typ_f6c220_idx'), models.Index(fields=['posted_at'], name='jobs_job_posted__7edcdf_idx'), models.Index(fields=['category'], name='jobs_job_categor_24d294_idx')],
            },
        ),
    ]
