# Generated by Django 6.0.2 on 2026-05-19 05:06

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_alter_job_options_job_jobs_job_is_acti_b6ae73_idx'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='job',
            index=models.Index(fields=['is_active', 'job_type'], name='jobs_job_is_acti_f8cdc7_idx'),
        ),
    ]
