# Generated by Django 6.0.2 on 2026-05-19 05:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_job_jobs_job_is_acti_f8cdc7_idx'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='vacancy',
            field=models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(limit_value=1, message='Vacancy must be equal or greater than 1')]),
        ),
    ]
