# Generated by Django 6.0.2 on 2026-05-19 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0004_job_vacancy'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='expericen',
            field=models.CharField(choices=[('senior', 'Senior'), ('mid', 'Mid'), ('junior', 'Junior')], default='junior', max_length=6),
        ),
    ]
