# Generated by Django 6.0.2 on 2026-05-20 04:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0006_currency'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='currency',
            options={'verbose_name_plural': 'Currencies'},
        ),
        migrations.AlterModelOptions(
            name='jobcategory',
            options={'ordering': ['title'], 'verbose_name_plural': 'Job Categories'},
        ),
    ]
