# Generated by Django 6.0.2 on 2026-05-20 04:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0007_alter_currency_options_alter_jobcategory_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='currency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='jobs.currency'),
        ),
    ]
