# Generated by Django 6.0.2 on 2026-05-20 04:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0009_job_short_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='currency',
            field=models.ForeignKey(blank=True, help_text='If you left this field blank , then it will set to USD', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='jobs', to='jobs.currency'),
        ),
    ]
