# Generated by Django 6.0.2 on 2026-05-20 12:32

import cloudinary.models
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0010_alter_job_currency'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('cover_letter', cloudinary.models.CloudinaryField(max_length=255)),
                ('resume', cloudinary.models.CloudinaryField(max_length=255)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('shortlisted', 'Shortlisted')], default='pending', max_length=15)),
                ('hr_messages', models.TextField(blank=True, null=True)),
                ('applied_at', models.DateTimeField(auto_now_add=True)),
                ('candidate', models.ForeignKey(limit_choices_to={'user_type': 'developer'}, on_delete=django.db.models.deletion.CASCADE, related_name='applications', to=settings.AUTH_USER_MODEL)),
                ('job', models.ForeignKey(limit_choices_to={'is_active': True}, on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='jobs.job')),
            ],
            options={
                'ordering': ['job', 'applied_at'],
                'indexes': [models.Index(fields=['job'], name='jobs_applic_job_id_a2c43b_idx'), models.Index(fields=['job', 'candidate'], name='jobs_applic_job_id_e3b368_idx')],
                'unique_together': {('job', 'candidate')},
            },
        ),
    ]
