# Generated by Django 6.0.2 on 2026-05-21 04:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0011_application'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job',
            old_name='expericen',
            new_name='experience',
        ),
    ]
