# Generated by Django 6.0.2 on 2026-06-06 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0013_alter_job_company'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='job_type',
            field=models.CharField(choices=[('Intern', 'intern'), ('Full time', 'full_time'), ('Part time', 'part_time'), ('contract', 'Contract'), ('remote', 'Remote')], max_length=20),
        ),
    ]
