# Generated by Django 6.0.2 on 2026-06-06 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0014_alter_job_job_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='job_type',
            field=models.CharField(choices=[('intern', 'Intern'), ('full_time', 'Full time'), ('part_time', 'Part time'), ('contract', 'Contract'), ('remote', 'Remote')], max_length=20),
        ),
    ]
