# Generated by Django 6.0.2 on 2026-06-06 08:09

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0015_alter_job_job_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='application',
            name='jobs_applic_job_id_e3b368_idx',
        ),
        migrations.RemoveIndex(
            model_name='job',
            name='jobs_job_company_9ee5ea_idx',
        ),
        migrations.RenameField(
            model_name='application',
            old_name='candidate',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='job',
            old_name='company',
            new_name='user',
        ),
        migrations.AlterUniqueTogether(
            name='application',
            unique_together={('job', 'user')},
        ),
        migrations.AddIndex(
            model_name='application',
            index=models.Index(fields=['job', 'user'], name='jobs_applic_job_id_a088c0_idx'),
        ),
        migrations.AddIndex(
            model_name='job',
            index=models.Index(fields=['user'], name='jobs_job_user_id_d7ccac_idx'),
        ),
    ]
