# Generated by Django 6.0.2 on 2026-06-16 17:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0016_remove_application_jobs_applic_job_id_e3b368_idx_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='application',
            old_name='hr_messages',
            new_name='hr_message',
        ),
    ]
