# Generated by Django 6.0.2 on 2026-06-20 06:59

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0018_skill_job_skills'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='application',
            options={'ordering': ['job', '-created_at']},
        ),
        migrations.AlterModelOptions(
            name='job',
            options={'ordering': ['-created_at']},
        ),
        migrations.RemoveIndex(
            model_name='job',
            name='jobs_job_posted__7edcdf_idx',
        ),
        migrations.RenameField(
            model_name='application',
            old_name='applied_at',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='job',
            old_name='posted_at',
            new_name='created_at',
        ),
        migrations.AddIndex(
            model_name='job',
            index=models.Index(fields=['created_at'], name='jobs_job_created_1b3a4d_idx'),
        ),
    ]
