# Generated by Django 6.0.2 on 2026-06-20 07:03

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0019_alter_application_options_alter_job_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='application',
            options={'ordering': ['job', 'applied_at']},
        ),
        migrations.AlterModelOptions(
            name='job',
            options={'ordering': ['-posted_at']},
        ),
        migrations.RemoveIndex(
            model_name='job',
            name='jobs_job_created_1b3a4d_idx',
        ),
        migrations.RenameField(
            model_name='application',
            old_name='created_at',
            new_name='applied_at',
        ),
        migrations.RenameField(
            model_name='job',
            old_name='created_at',
            new_name='posted_at',
        ),
        migrations.AddIndex(
            model_name='job',
            index=models.Index(fields=['posted_at'], name='jobs_job_posted__7edcdf_idx'),
        ),
    ]
