# Generated by Django 6.0.2 on 2026-07-11 12:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0022_alter_application_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='hr_message',
        ),
    ]
