# Generated by Django 6.0.2 on 2026-07-18 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0026_alter_application_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('under_review', 'Under Review'), ('shortlisted', 'Shortlisted'), ('interview_scheduled', 'Interview Scheduled'), ('offered', 'Offered'), ('hired', 'Hired'), ('offer_declined', 'Offer Declined'), ('rejected_by_hr', 'Rejected by HR'), ('withdrawn', 'Withdrawn')], default='pending', max_length=20),
        ),
    ]
