# Generated by Django 6.0.2 on 2026-05-01 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('session', '0002_customuser_joined_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='gender',
            field=models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('Third', 'third'), ('transgender', 'Transgender')], default='male', max_length=12),
        ),
    ]
