# Generated by Django 6.0.2 on 2026-05-01 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('session', '0004_follow'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='follow',
            index=models.Index(fields=['following'], name='session_fol_followi_45acc6_idx'),
        ),
        migrations.AddIndex(
            model_name='follow',
            index=models.Index(fields=['follower'], name='session_fol_followe_3e19be_idx'),
        ),
    ]
