# Generated by Django 6.0.2 on 2026-05-13 13:38

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('session', '0005_follow_session_fol_followi_45acc6_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('report_type', models.CharField(blank=True, choices=[('spam', 'Spam'), ('fake', 'Fake Information'), ('harassment', 'Harassment'), ('copyright', 'Copyright'), ('nsfw', 'NSFW'), ('scam', 'Scam'), ('other', 'Other')], max_length=20, null=True)),
                ('reason', models.TextField(blank=True, null=True)),
                ('reported_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('object_id', models.UUIDField()),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('reported_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to=settings.AUTH_USER_MODEL)),
                ('reporter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='my_reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['content_type', 'object_id'], name='session_rep_content_66459f_idx')],
                'unique_together': {('reported_profile', 'reporter')},
            },
        ),
    ]
