# Generated by Django 6.0.2 on 2026-05-13 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('session', '0006_report'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='report',
            unique_together={('reporter', 'content_type', 'object_id')},
        ),
        migrations.AddIndex(
            model_name='report',
            index=models.Index(fields=['reporter'], name='session_rep_reporte_12b074_idx'),
        ),
        migrations.AddIndex(
            model_name='report',
            index=models.Index(fields=['report_type'], name='session_rep_report__df3113_idx'),
        ),
        migrations.AddIndex(
            model_name='report',
            index=models.Index(fields=['reported_at'], name='session_rep_reporte_592d9b_idx'),
        ),
    ]
