# Generated by Django 6.0.2 on 2026-05-13 15:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('session', '0009_customuser_bio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report',
            name='reported_profile',
        ),
    ]
