# Generated by Django 6.0.2 on 2026-05-18 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('session', '0010_remove_report_reported_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[('company', 'Company'), ('developer', 'Developer')], default='developer', max_length=9),
        ),
    ]
