# Generated by Django 6.0.2 on 2026-05-22 14:48

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('session', '0011_customuser_user_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bookmark',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('object_id', models.UUIDField()),
                ('bookmarked_at', models.DateTimeField(auto_now_add=True)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookmarks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-bookmarked_at'],
                'indexes': [models.Index(fields=['user', 'content_type', 'object_id'], name='session_boo_user_id_f42954_idx'), models.Index(fields=['user'], name='session_boo_user_id_50d79e_idx'), models.Index(fields=['user', 'content_type'], name='session_boo_user_id_3da5d4_idx')],
                'constraints': [models.UniqueConstraint(fields=('user', 'content_type', 'object_id'), name='unique_user_bookmark')],
            },
        ),
    ]
