# Generated by Django 6.0.2 on 2026-05-26 11:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('session', '0012_bookmark'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='report',
            unique_together=None,
        ),
        migrations.RemoveIndex(
            model_name='report',
            name='session_rep_content_66459f_idx',
        ),
        migrations.RemoveIndex(
            model_name='report',
            name='session_rep_reporte_12b074_idx',
        ),
        migrations.RemoveIndex(
            model_name='report',
            name='session_rep_report__df3113_idx',
        ),
        migrations.RemoveIndex(
            model_name='report',
            name='session_rep_reporte_592d9b_idx',
        ),
        migrations.DeleteModel(
            name='Report',
        ),
    ]
