# Generated by Django 6.0.2 on 2026-05-29 13:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('session', '0013_alter_report_unique_together_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='bookmark',
            name='session_boo_user_id_f42954_idx',
        ),
        migrations.RemoveIndex(
            model_name='bookmark',
            name='session_boo_user_id_50d79e_idx',
        ),
        migrations.RemoveIndex(
            model_name='bookmark',
            name='session_boo_user_id_3da5d4_idx',
        ),
        migrations.RemoveConstraint(
            model_name='bookmark',
            name='unique_user_bookmark',
        ),
        migrations.DeleteModel(
            name='Bookmark',
        ),
    ]
