# Generated by Django 6.0.2 on 2026-06-11 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('session', '0014_remove_bookmark_session_boo_user_id_f42954_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[('company', 'Company'), ('developer', 'Developer')], default='developer', max_length=9, null=True),
        ),
    ]
