# Generated by Django 6.0.2 on 2026-06-11 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('session', '0015_alter_customuser_user_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[('company', 'Company'), ('developer', 'Developer')], default='developer', max_length=9),
        ),
    ]
