# Generated by Django 6.0.2 on 2026-07-02 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('session', '0016_alter_customuser_user_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='gender',
            field=models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('third', 'Third'), ('transgender', 'Transgender')], default='male', max_length=12),
        ),
    ]
