# Generated by Django 6.0.2 on 2026-06-12 15:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('JOB_POSTED', 'Job posted'), ('APPLICATION_SUBMITTED', 'Application submitted'), ('APPLICATION_ACCEPTED', 'Application accepted'), ('APPLICATION_REJECTED', 'Application rejected'), ('APPLICATION_SHORTLISTED', 'Application shortlisted'), ('POST_CREATED', 'Post created'), ('POST_VOTED', 'Post voted'), ('POST_REVIEWED', 'Post reviewed'), ('COMMENT_POSTED', 'Comment posted'), ('COMMENT_REPLIED', 'Comment replied'), ('REPORT_ADDED', 'Report added')], max_length=50)),
                ('object_id', models.UUIDField(null=True)),
                ('content', models.CharField(max_length=300)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_triggerer', to=settings.AUTH_USER_MODEL)),
                ('content_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['recipient', 'is_read'], name='notificatio_recipie_dd6756_idx'), models.Index(fields=['recipient'], name='notificatio_recipie_33f584_idx'), models.Index(fields=['recipient', 'created_at', 'is_read'], name='notificatio_recipie_80b28f_idx')],
            },
        ),
    ]
