# Generated by Django 6.0.2 on 2026-05-26 06:09

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('report_type', models.CharField(blank=True, choices=[('spam', 'Spam'), ('fake', 'Fake Information'), ('harassment', 'Harassment'), ('copyright', 'Copyright'), ('nsfw', 'NSFW'), ('scam', 'Scam'), ('other', 'Other')], max_length=20, null=True)),
                ('reason', models.TextField(blank=True, null=True)),
                ('reported_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('object_id', models.UUIDField()),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('reporter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='my_reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['content_type', 'object_id'], name='report_repo_content_7ea2c7_idx'), models.Index(fields=['reporter'], name='report_repo_reporte_4ef0c1_idx'), models.Index(fields=['report_type'], name='report_repo_report__00de4f_idx'), models.Index(fields=['reported_at'], name='report_repo_reporte_4a4c90_idx')],
                'unique_together': {('reporter', 'content_type', 'object_id')},
            },
        ),
    ]
