# Generated by Django 6.0.2 on 2026-06-20 07:00

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('report', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='report',
            name='report_repo_reporte_4a4c90_idx',
        ),
        migrations.RenameField(
            model_name='report',
            old_name='reported_at',
            new_name='created_at',
        ),
        migrations.AddIndex(
            model_name='report',
            index=models.Index(fields=['created_at'], name='report_repo_created_be46cb_idx'),
        ),
    ]
