# Generated by Django 6.0.2 on 2026-05-28 14:24

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('vote_type', models.CharField(choices=[('upvote', 'Up Vote'), ('downvote', 'Down Vote')], max_length=12)),
                ('object_id', models.UUIDField()),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-added_at'],
                'indexes': [models.Index(fields=['user'], name='vote_vote_user_id_6cc2c1_idx'), models.Index(fields=['user', 'content_type'], name='vote_vote_user_id_6b7a47_idx'), models.Index(fields=['user', 'content_type', 'object_id'], name='vote_vote_user_id_e23514_idx')],
                'unique_together': {('user', 'content_type', 'object_id')},
            },
        ),
    ]
