# Generated by Django 6.0.2 on 2026-05-29 11:37

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('vote', '0002_vote_vote_vote_content_b3cc75_idx'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='vote',
            name='vote_vote_user_id_6b7a47_idx',
        ),
        migrations.RemoveIndex(
            model_name='vote',
            name='vote_vote_content_b3cc75_idx',
        ),
        migrations.AddIndex(
            model_name='vote',
            index=models.Index(fields=['content_type', 'object_id'], name='vote_vote_content_a520b4_idx'),
        ),
    ]
