# Generated by Django 6.0.2 on 2026-05-30 06:06

import cloudinary.models
import django.db.models.deletion
import django_summernote.fields
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('title',), name='unique_title_constrain')],
            },
        ),
        migrations.CreateModel(
            name='Discussion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=120)),
                ('banner', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True)),
                ('short_description', models.TextField(max_length=200)),
                ('detail', django_summernote.fields.SummernoteTextField()),
                ('posted_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(limit_choices_to={'is_active': True}, on_delete=django.db.models.deletion.CASCADE, related_name='discussions', to=settings.AUTH_USER_MODEL)),
                ('tags', models.ManyToManyField(blank=True, related_name='discussions', to='discussion.tag')),
            ],
            options={
                'ordering': ['-posted_at'],
                'indexes': [models.Index(fields=['author'], name='discussion__author__b9ddb8_idx'), models.Index(fields=['posted_at'], name='discussion__posted__975cb5_idx')],
            },
        ),
    ]
