# Generated by Django 6.0.2 on 2026-06-06 08:56

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discussion', '0002_alter_discussion_author'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='discussion',
            name='discussion__author__b9ddb8_idx',
        ),
        migrations.RenameField(
            model_name='discussion',
            old_name='author',
            new_name='user',
        ),
        migrations.AddIndex(
            model_name='discussion',
            index=models.Index(fields=['user'], name='discussion__user_id_dfc23a_idx'),
        ),
    ]
