# Generated by Django 6.0.2 on 2026-06-20 06:58

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discussion', '0003_remove_discussion_discussion__author__b9ddb8_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='discussion',
            options={'ordering': ['-created_at']},
        ),
        migrations.RemoveIndex(
            model_name='discussion',
            name='discussion__posted__975cb5_idx',
        ),
        migrations.RenameField(
            model_name='discussion',
            old_name='posted_at',
            new_name='created_at',
        ),
        migrations.AddIndex(
            model_name='discussion',
            index=models.Index(fields=['created_at'], name='discussion__created_dc291b_idx'),
        ),
    ]
