# Generated by Django 6.0.2 on 2026-06-20 07:03

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discussion', '0004_alter_discussion_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='discussion',
            options={'ordering': ['-posted_at']},
        ),
        migrations.RemoveIndex(
            model_name='discussion',
            name='discussion__created_dc291b_idx',
        ),
        migrations.RenameField(
            model_name='discussion',
            old_name='created_at',
            new_name='posted_at',
        ),
        migrations.AddIndex(
            model_name='discussion',
            index=models.Index(fields=['posted_at'], name='discussion__posted__975cb5_idx'),
        ),
    ]
