"""
Django settings for saas_com project.

Generated by 'django-admin startproject' using Django 6.0.4.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path
from dotenv import load_dotenv
import os
import sys
import dj_database_url 
import logging

load_dotenv()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv("DJANGO_SECRET_KEY")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv("DEBUG")

ALLOWED_HOSTS = os.getenv("ALLOWED_HOSTS" , "localhost 127.0.0.1").split()


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django_summernote',
    'session',
    'apps',
    'discussion',
    'cloudinary_storage',
    'cloudinary',
    'jobs',
    'report',
    'vote',
    'bookmark',
    'comment',
    'dashboard',
    'rest_framework',

]

AUTH_USER_MODEL = "session.CustomUser"
AUTHENTICATION_BACKENDS = [
    'session.backends.EmailBackend',
    'django.contrib.auth.backends.ModelBackend'
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware', 
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'saas_com.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'saas_com.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

try:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }
except:
    DATABASES = {
    'default': dj_database_url.config(
        # Replace this value with your local database's connection string.
        default=os.getenv('DATABASE_URL'),
        conn_max_age=600
    )
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Asia/Dhaka'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'
STATICFILES_DIRS = [
    BASE_DIR / "static"
]
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')
if not DEBUG:
    STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'

SUMMERNOTE_CONFIG = {

    # Or, you can set it to `False` to use SummernoteInplaceWidget by default - no iframe mode
    # In this case, you have to load Bootstrap/jQuery sources and dependencies manually.
    # Use this when you're already using Bootstrap/jQuery based themes.
    'iframe': True,

    # You can put custom Summernote settings
    'summernote': {
        # As an example, using Summernote Air-mode
        'airMode': False,

        # Change editor size
        'width': '100%',
        'height': '200px',

        # Use proper language setting automatically (default)
        'lang': LANGUAGE_CODE,

        # Toolbar customization
        'toolbar': [
            ['style', ['style']],
            ['font', ['bold', 'underline', 'clear']],
            ['fontname', ['fontname']],
            ['color', ['color']],
            ['para', ['ul', 'ol', 'paragraph']],
            ['table', ['table']],
            ['insert', ['link', 'picture', 'video']],
            ['view', ['fullscreen', 'codeview', 'help']],
        ],

        
    }
    
}

EMAIL_BACKEND='django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST='smtp.gmail.com'
EMAIL_PORT=587
EMAIL_USE_TLS=True
EMAIL_HOST_USER = os.getenv("EMAIL_HOST_USER")
EMAIL_HOST_PASSWORD = os.getenv("EMAIL_HOST_PASSWORD")
DEFAULT_FROM_EMAIL = EMAIL_HOST_USER

import cloudinary
cloudinary.config( 
  	cloud_name = os.getenv("CLOUDINARY_CLOUD_NAME"),
  	api_key = os.getenv("CLOUDINARY_API_KEY"),
  	api_secret = os.getenv("CLOUDINARY_API_SECRET"),
    secure = True,
)

STORAGES = {
    "default":{
        "BACKEND": "cloudinary_storage.storage.MediaCloudinaryStorage",
    },
    "staticfiles": {
        "BACKEND": "django.contrib.staticfiles.storage.StaticFilesStorage",
    },
}

INTERNAL_IPS = [
    "127.0.0.1",
    "localhost",
]

TESTING = "test" in sys.argv or "PYTEST_VERSION" in os.environ

if DEBUG:
    INSTALLED_APPS += [
        "debug_toolbar",
    ]

    MIDDLEWARE += [
        "debug_toolbar.middleware.DebugToolbarMiddleware",
    ]

LOGS_DIR = os.path.join(BASE_DIR , "logs")
os.makedirs(LOGS_DIR , exist_ok = True)
LOGGING = {

    'version': 1,

    'disable_existing_loggers': False,

    'formatters': {

        'verbose': {
            'format': "{levelname} | {asctime} | {name} | {module} | {funcName} | {message}",
            'style': "{",
        },

        'simple': {
            'format': "{levelname} | {message}",
            'style': "{",
        },
    },

    'handlers': {

        'console': {
            'class': 'logging.StreamHandler',
            'formatter': 'simple',
        },

        'apps_file': {
            'class': 'logging.FileHandler',
            'filename': BASE_DIR / "logs/apps.log",
            'formatter': 'verbose',
        },

        'discussion_file': {
            'class': 'logging.FileHandler',
            'filename': BASE_DIR / "logs/discussion.log",
            'formatter': 'verbose',
        },

        'jobs_file': {
            'class': 'logging.FileHandler',
            'filename': BASE_DIR / "logs/jobs.log",
            'formatter': 'verbose',
        },

        'bookmark_file': {
            'class': 'logging.FileHandler',
            'filename': BASE_DIR / "logs/bookmark.log",
            'formatter': 'verbose',
        },

        'comment_file': {
            'class': 'logging.FileHandler',
            'filename': BASE_DIR / "logs/comment.log",
            'formatter': 'verbose',
        },

        'report_file': {
            'class': 'logging.FileHandler',
            'filename': BASE_DIR / "logs/report.log",
            'formatter': 'verbose',
        },

        'error_file': {
            'class': 'logging.FileHandler',
            'filename': BASE_DIR / "logs/error.log",
            'formatter': 'verbose',
            'level': 'ERROR',
        },

        'security_file': {
            'class': 'logging.FileHandler',
            'filename': BASE_DIR / "logs/security.log",
            'formatter': 'verbose',
            'level': 'WARNING',
        },
    },

    'loggers': {

        'django': {
            'handlers': ['console', 'error_file'],
            'level': 'INFO',
            'propagate': True,
        },

        'apps': {
            'handlers': ['console', 'apps_file', 'error_file'],
            'level': 'INFO',
            'propagate': False,
        },

        'discussion': {
            'handlers': ['console', 'discussion_file', 'error_file'],
            'level': 'DEBUG',
            'propagate': False,
        },

        'jobs': {
            'handlers': ['console', 'jobs_file', 'error_file'],
            'level': 'INFO',
            'propagate': False,
        },

        'bookmark': {
            'handlers': ['console', 'bookmark_file', 'error_file'],
            'level': 'INFO',
            'propagate': False,
        },

        'comment': {
            'handlers': ['console', 'comment_file', 'error_file'],
            'level': 'INFO',
            'propagate': False,
        },

        'report': {
            'handlers': ['console', 'report_file', 'error_file'],
            'level': 'WARNING',
            'propagate': False,
        },

        'security': {
            'handlers': ['console', 'security_file', 'error_file'],
            'level': 'WARNING',
            'propagate': False,
        },
    },

    'root': {
        'handlers': ['console', 'error_file'],
        'level': 'INFO',
    },
}