# Generated by Django 6.0.2 on 2026-06-01 05:03

import django.db.models.deletion
import django_summernote.fields
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('content', django_summernote.fields.SummernoteTextField()),
                ('object_id', models.UUIDField()),
                ('posted_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to=settings.AUTH_USER_MODEL)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
            options={
                'ordering': ['-posted_at'],
                'indexes': [models.Index(fields=['author'], name='comment_com_author__537842_idx'), models.Index(fields=['content_type', 'object_id'], name='comment_com_content_209058_idx'), models.Index(fields=['posted_at'], name='comment_com_posted__57a480_idx')],
            },
        ),
    ]
