# Generated by Django 6.0.2 on 2026-06-06 08:56

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0002_comment_parent_and_more'),
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='comment',
            name='comment_com_author__537842_idx',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='author',
            new_name='user',
        ),
        migrations.AddIndex(
            model_name='comment',
            index=models.Index(fields=['user'], name='comment_com_user_id_85c117_idx'),
        ),
    ]
