# Generated by Django 6.0.2 on 2026-06-20 06:57

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0003_remove_comment_comment_com_author__537842_idx_and_more'),
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-created_at']},
        ),
        migrations.RemoveIndex(
            model_name='comment',
            name='comment_com_posted__57a480_idx',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='posted_at',
            new_name='created_at',
        ),
        migrations.AddIndex(
            model_name='comment',
            index=models.Index(fields=['created_at'], name='comment_com_created_a4e7bf_idx'),
        ),
    ]
