# Generated by Django 6.0.2 on 2026-04-30 17:25

import cloudinary.models
import django.db.models.deletion
import django_summernote.fields
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='App',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=70)),
                ('logo', cloudinary.models.CloudinaryField(max_length=255, verbose_name='Logo')),
                ('developed_at', models.DateField(blank=True, null=True)),
                ('detail', django_summernote.fields.SummernoteTextField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=10)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ManyToManyField(blank=True, related_name='apps', to='apps.category')),
                ('founder', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='apps', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-added_at'],
            },
        ),
        migrations.CreateModel(
            name='AppImages',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('image', cloudinary.models.CloudinaryField(max_length=255, verbose_name='App Image')),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('app', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='app_images', to='apps.app')),
            ],
            options={
                'ordering': ['-added_at'],
            },
        ),
        migrations.AddIndex(
            model_name='app',
            index=models.Index(fields=['added_at'], name='apps_app_added_a_a8bf50_idx'),
        ),
        migrations.AddIndex(
            model_name='app',
            index=models.Index(fields=['status'], name='apps_app_status_bb8880_idx'),
        ),
    ]
