# Generated by Django 6.0.2 on 2026-05-01 09:03

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0002_app_appimages_app_apps_app_added_a_a8bf50_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AppVote',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('vote_type', models.CharField(choices=[('upvote', 'Up Vote'), ('downvote', 'Down Vote')], max_length=12)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('app', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='app_votes', to='apps.app')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='app_votes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['app'], name='apps_appvot_app_id_0d4a74_idx'), models.Index(fields=['user'], name='apps_appvot_user_id_7541c5_idx'), models.Index(fields=['app', 'vote_type'], name='apps_appvot_app_id_1f2456_idx')],
                'unique_together': {('user', 'app')},
            },
        ),
    ]
