# Generated by Django 6.0.2 on 2026-05-01 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0003_appvote'),
    ]

    operations = [
        migrations.AddField(
            model_name='app',
            name='short_description',
            field=models.TextField(blank=True, max_length=200),
        ),
    ]
