# Generated by Django 6.0.2 on 2026-05-11 02:28

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0006_review'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReviewVote',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('vote_type', models.CharField(choices=[('upvote', 'Up Vote'), ('downvote', 'Down Vote')], max_length=12)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('review', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review_votes', to='apps.review')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review_votes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['review'], name='apps_review_review__2b16e1_idx'), models.Index(fields=['review', 'vote_type'], name='apps_review_review__ada634_idx')],
                'unique_together': {('user', 'review')},
            },
        ),
    ]
