# Generated by Django 6.0.2 on 2026-05-29 13:43

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0007_reviewvote'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='appvote',
            unique_together=None,
        ),
        migrations.RemoveIndex(
            model_name='appvote',
            name='apps_appvot_app_id_0d4a74_idx',
        ),
        migrations.RemoveIndex(
            model_name='appvote',
            name='apps_appvot_user_id_7541c5_idx',
        ),
        migrations.RemoveIndex(
            model_name='appvote',
            name='apps_appvot_app_id_1f2456_idx',
        ),
        migrations.AlterUniqueTogether(
            name='reviewvote',
            unique_together=None,
        ),
        migrations.RemoveIndex(
            model_name='reviewvote',
            name='apps_review_review__2b16e1_idx',
        ),
        migrations.RemoveIndex(
            model_name='reviewvote',
            name='apps_review_review__ada634_idx',
        ),
        migrations.AddIndex(
            model_name='app',
            index=models.Index(fields=['founder'], name='apps_app_founder_fa9ce5_idx'),
        ),
        migrations.RemoveField(
            model_name='reviewvote',
            name='review',
        ),
        migrations.RemoveField(
            model_name='reviewvote',
            name='user',
        ),
        migrations.DeleteModel(
            name='AppVote',
        ),
        migrations.DeleteModel(
            name='ReviewVote',
        ),
    ]
