# Generated by Django 6.0.2 on 2026-06-06 08:45

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0009_review_rating'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='app',
            name='apps_app_founder_fa9ce5_idx',
        ),
        migrations.RenameField(
            model_name='app',
            old_name='founder',
            new_name='user',
        ),
        migrations.AddIndex(
            model_name='app',
            index=models.Index(fields=['user'], name='apps_app_user_id_cfccab_idx'),
        ),
        migrations.RemoveField(
            model_name='app',
            name='tags',
        ),
        migrations.DeleteModel(
            name='Tag',
        ),
    ]
