# Generated by Django 6.0.2 on 2026-06-19 12:09

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0010_remove_app_apps_app_founder_fa9ce5_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='app',
            name='logo',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='appimages',
            name='image',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='image'),
        ),
    ]
