# Generated by Django 6.0.2 on 2026-06-19 12:24

import cloudinary.models
import django.core.validators
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0011_alter_app_logo_alter_appimages_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='app',
            name='logo',
            field=cloudinary.models.CloudinaryField(max_length=255, validators=[django.core.validators.validate_image_file_extension], verbose_name='image'),
        ),
    ]
