# Generated by Django 6.0.2 on 2026-06-19 12:30

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0012_alter_app_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='app',
            name='logo',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='Logo'),
        ),
        migrations.AlterField(
            model_name='appimages',
            name='image',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='App Image'),
        ),
    ]
