# Generated by Django 6.0.2 on 2026-06-19 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0013_alter_app_logo_alter_appimages_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appimages',
            name='image',
            field=models.ImageField(upload_to='temp/app_images/'),
        ),
    ]
