# Generated by Django 6.0.2 on 2026-06-19 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0014_alter_appimages_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='appimages',
            name='url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
