# Generated by Django 6.0.2 on 2026-06-19 14:24

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0015_appimages_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appimages',
            name='url',
        ),
        migrations.AlterField(
            model_name='appimages',
            name='image',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='App Image'),
        ),
    ]
