# Generated by Django 6.0.2 on 2026-06-20 06:56

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0016_remove_appimages_url_alter_appimages_image'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='app',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='appimages',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='review',
            options={'ordering': ['-created_at']},
        ),
        migrations.RemoveIndex(
            model_name='app',
            name='apps_app_added_a_a8bf50_idx',
        ),
        migrations.RenameField(
            model_name='app',
            old_name='added_at',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='appimages',
            old_name='added_at',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='review',
            old_name='added_at',
            new_name='created_at',
        ),
        migrations.AddIndex(
            model_name='app',
            index=models.Index(fields=['created_at'], name='apps_app_created_fdae32_idx'),
        ),
    ]
